name: Build sqlite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  version: "3400000"
  release_year: "2022"
  docker_image: "static-sqlite"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build sqlite
        working-directory: ./docker
        run: sudo docker build --rm --no-cache=true -t "${docker_image}" . --build-arg URL_SQLITE_SOURCE_ZIP="https://www.sqlite.org/${release_year}/sqlite-amalgamation-${version}.zip" --build-arg COMPRESS_SQLITE3="upx"
      - name: Extract binary from docker image
        uses: shrink/actions-docker-extract@v2
        id: extract
        with:
          image: ${{env.docker_image}}
          path: /app/sqlite-amalgamation-${{env.version}}/sqlite3
      - name: Upload sqlite binary artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: sqlite-${{env.version}}
